template = "https://github.com/giellalt/template-lang-und"
rev_id = 301
template_sha = "14c7684fb7ae87003fef7c476a4f619d2addefa7"

[replacements]
__GLOTTOLOG_ID__ = "swed1254"
__REPO__ = "lang-swe"
__UND2C__ = "sv"
__UNDEFINED__ = "Swedish"
__UND__ = "swe"
