template = "https://github.com/giellalt/template-lang-und"
rev_id = 305
template_sha = "64df68fecb78cef7f709bfe67c09affe7c3b0c38"

[replacements]
__GLOTTOLOG_ID__ = "swed1254"
__REPO__ = "lang-swe"
__UND2C__ = "sv"
__UNDEFINED__ = "Swedish"
__UND__ = "swe"
