template = "https://github.com/giellalt/template-lang-und"
rev_id = 330
template_sha = "ca06c138bb7dc0942a15e60b710a001352e6ebde"

[replacements]
__GLOTTOLOG_ID__ = "swed1254"
__REPO__ = "lang-swe"
__UND2C__ = "sv"
__UNDEFINED__ = "Swedish"
__UND__ = "swe"
