[package]
name = "swe"
human_name = "Swedish"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.swe]
filename = "sv-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-swe"
platform = "windows"
uuid = "1D7005F8-D195-4760-8F46-646D2AD64BB9"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.sv"
package = "speller-swe"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-swe-mso"
platform = "windows"
uuid = "F8B27250-9843-4E98-998E-D5E544CFC2AF"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-swe"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
